### ISSUE TITLE
yarn add webix-vue impossible

### ISSUE THREAD

**Issue by GuillaumeM59** [webix-hub/webix-vue#2]
Is package.json not correct?

from https://yarnpkg.com/en/package/webix-vue

$ yarn add webix-vue

return:

yarn add v0.27.5
[1/4] Resolving packages...
error Received malformed response from registry for "webix-vue". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

is registry down?

**Comment by mkozhukh** [comment]
The npm package name is "vue-webix", so the command will be ```yarn add vue-webix``` 
https://www.npmjs.com/package/vue-webix
Sorry for confusion
